using Hive.Persistence;
using Microsoft.Data.SqlClient;

namespace Hive.Tests.TestInfrastructure;

/// <summary>
/// A uniquely named SQL Server database lease owned by one Hive.Tests test or fixture.
/// The physical name is generated by <see cref="SqlTestDatabaseLifecycle"/>; the
/// supplied name is only a diagnostic label.
/// </summary>
internal sealed class PersistenceTestDatabase : IDisposable, IAsyncDisposable
{
    private readonly SqlTestDatabaseLifecycle.OwnedDatabase _ownedDatabase;
    private int _disposed;

    public PersistenceTestDatabase(string databaseName)
    {
        _ownedDatabase = SqlTestDatabaseLifecycle.Create(databaseName);
        DatabaseName = _ownedDatabase.DatabaseName;
        Options = new HiveDatabaseOptions(
            _ownedDatabase.ConnectionString,
            createDatabaseIfMissing: true);
    }

    public string DatabaseName { get; }

    public HiveDatabaseOptions Options { get; }

    public void Reset()
    {
        using var connection = new SqlConnection(Options.ConnectionString);
        connection.Open();

        using var command = connection.CreateCommand();
        command.CommandText = """
            IF OBJECT_ID(N'dbo.TR_HiveEventLog_RollbackProbe', N'TR') IS NOT NULL
                DROP TRIGGER [dbo].[TR_HiveEventLog_RollbackProbe];

            IF OBJECT_ID(N'dbo.HiveWorkItemAttachments', N'U') IS NOT NULL
                DROP TABLE [dbo].[HiveWorkItemAttachments];

            IF OBJECT_ID(N'dbo.HiveWorkItems', N'U') IS NOT NULL
                DROP TABLE [dbo].[HiveWorkItems];

            IF OBJECT_ID(N'dbo.HiveAgentWorkState', N'U') IS NOT NULL
                DROP TABLE [dbo].[HiveAgentWorkState];

            IF OBJECT_ID(N'dbo.HiveEventOutbox', N'U') IS NOT NULL
                DROP TABLE [dbo].[HiveEventOutbox];

            IF OBJECT_ID(N'dbo.HiveEventSnapshots', N'U') IS NOT NULL
                DROP TABLE [dbo].[HiveEventSnapshots];

            IF OBJECT_ID(N'dbo.HiveEventLog', N'U') IS NOT NULL
                DROP TABLE [dbo].[HiveEventLog];

            IF OBJECT_ID(N'dbo.HiveAgentDefinitions', N'U') IS NOT NULL
                DROP TABLE [dbo].[HiveAgentDefinitions];

            IF OBJECT_ID(N'dbo.HiveSecrets', N'U') IS NOT NULL
                DROP TABLE [dbo].[HiveSecrets];

            IF OBJECT_ID(N'dbo.HiveExecutionTargetFavorites', N'U') IS NOT NULL
                DROP TABLE [dbo].[HiveExecutionTargetFavorites];

            IF OBJECT_ID(N'dbo.HiveExecutionTargets', N'U') IS NOT NULL
                DROP TABLE [dbo].[HiveExecutionTargets];

            IF OBJECT_ID(N'dbo.HiveProviderAccounts', N'U') IS NOT NULL
                DROP TABLE [dbo].[HiveProviderAccounts];

            IF OBJECT_ID(N'dbo.HiveProviders', N'U') IS NOT NULL
                DROP TABLE [dbo].[HiveProviders];

            IF OBJECT_ID(N'dbo.HiveMigrationJournal', N'U') IS NOT NULL
                DROP TABLE [dbo].[HiveMigrationJournal];

            IF OBJECT_ID(N'dbo.HiveSchemaVersion', N'U') IS NOT NULL
                DROP TABLE [dbo].[HiveSchemaVersion];

            IF OBJECT_ID(N'dbo.HiveMigrationFailureProbe', N'U') IS NOT NULL
                DROP TABLE [dbo].[HiveMigrationFailureProbe];
            """;
        command.ExecuteNonQuery();
    }

    public void Dispose() =>
        DisposeAsync().AsTask().GetAwaiter().GetResult();

    public async ValueTask DisposeAsync()
    {
        if (Interlocked.CompareExchange(ref _disposed, 1, 0) != 0)
            return;

        try
        {
            await SqlTestDatabaseLifecycle.DropOwnedAsync(_ownedDatabase)
                .ConfigureAwait(false);
        }
        catch
        {
            // Permit a caller or a later disposal attempt to retry after a
            // transient failure. The exception remains observable to the test.
            Volatile.Write(ref _disposed, 0);
            throw;
        }
    }
}
